### ISSUE TITLE
Issue in the bootstrap3 template after upgrading dokuwiki to rc2020-06-09 "Hogfather"

### ISSUE THREAD

**Issue by albertvilabsc** [giterlizzi/dokuwiki-template-bootstrap3#490] opened 2020-06-18 12:26 UTC
### Description
After upgrading dokuwiki to rc2020-06-09 "Hogfather". The menu in the upper right corner does not display the submenu.

### Steps to reproduce
Move the mouse to the menu in the upper right corner, the submenu will not be displayed.

**Expected behavior:** When I will make click in the upper right corners the submenu should displays.
**Actual behavior:** When I make click in the upper right corners the submenu doesn't appears.

### Versions

* [Bootstrap3 Template]
v2020-04-04 (hotfix/20200505)
* [DokuWiki]
rc2020-06-09 "Hogfather"
* [Plugins]
User Manager
DokuWiki Upgrade Plugin
styling plugin
smtp plugin
safefnrecode plugin
Revert Manager 
Popularity Feedback Plugin
Info Plugin
Extension Manager
Configuration Manager
comment 
Plain Auth Plugin
authpdo plugin
LDAP Auth Plugin
Active Directory Auth Plugin
ACL Manager

* [PHP]
PHP 7.0.7 (cli) ( NTS )
* [Browser]
Google chrome: 83.0.4103.106 (Build oficial) (64 bits)

### Screenshots or Logs
![image](https://user-images.githubusercontent.com/67104441/85017927-943f9280-b16c-11ea-8f2b-f15c7165940a.png)

### Sample page or snippet
You can see the issue in this wiki: https://earth.bsc.es/fragment_2/doku.php

**Comment by giterlizzi** [comment] 2020-06-18 15:38
Duplicate of #483

**Comment by giterlizzi** [comment] 2020-06-18 15:39
Please install the develop version of template and/or disable "defer_js" option in Configuration Settings.

**Comment by albertvilabsc** [comment] 2020-06-22 07:41
@giterlizzi 
Perfect! 
And in what site can I download the develop version of the template?
The normal version of the template, in a future, with one update, will have a solution? Or only with the develop version?
Thanks!

**Comment by Genetik57** [comment] 2020-06-22 18:17
@giterlizzi Mobile navbar does not work but thanks for you hard work :)

**Comment by kaktux** [comment] 2020-06-26 06:19
Thx @giterlizzi 
Can confirm that the problem existed after update - but can be solved by disabling defer_js.

Anyone having trouble accessing the admin page - the link you need looks like
https://yourdomain.com/doku.php/start?do=admin&page=plugins

**Comment by DrakMrak** [comment] 2020-06-26 08:06
I see one more problem... (PHP 7.3 / safe mode: ON)
in file: **simple_html_dom.php**

I must comment this
24: //set_time_limit(0);
25: //ini_set('max_execution_time', 0); - not set to zero!! (5-300)

**My provider** does not allow set **set_time_limit(X)** - and dokuwiki appear warning message when trying to change it! 
"Warning: set_time_limit() has been disabled for security reasons in /data/web/virtuals/52324/virtual/www/lib/tpl/bootstrap3/inc/simple_html_dom.php on line 24"

I can set **max_execution_time** from 5 to 300, and I have set 300 - but it is not always enough!
I can not set **set_time_limit(0)** - among other things, this is not recommended for security reasons !! 

"Warning - This function has no effect when PHP is running in **safe mode.** There is no workaround other than turning off safe mode or changing the time limit in the php.ini."

**Comment by spokekiller** [comment] 2020-06-26 13:54
> I see one more problem... (PHP 7.3 / safe mode: ON)

Please do not hop on a completely different issue with your problem. Please open a new bug, if you cannot find a similar bug already opened.

**Comment by spokekiller** [comment] 2020-06-26 15:02
I am sorry, but **neither** the develop branch nor disabling defer_js or both combined work for me.
I still have the effect, that the link underneath the admin icon is always identical to the the current page. Same for the user logo.

Config Panel Shows:
Release rc-2020-06-09 "Hogfather" RC3
Template v2020-04-04 (develop/20200611)
for debugging purposes, find the source of a buggy page here: https://gist.github.com/spokekiller/85cc8bccea6664eb6c70d9f4a5a0d6a4

**Comment by giterlizzi** [comment] 2020-06-27 10:17
@spokekiller You have plugins installed?
Please check your JS console.

Thanks

**Comment by spokekiller** [comment] 2020-06-27 14:58
@giterlizzi 
Yes, I do ... but maybe I did not state clearly. I meant the navbar at the very top. (not the share, email, print bar). The one with the wrench, pencil, ... 

My JS Console (FF 77.0.1) shows no errors... any ideas left? 

My plugin dir shows:
`acl
action.php
admin.php
authad
authldap
authmysql
authpdo
authpgsql
auth.php
authplain
bootswrapper
config
dw2pdf
edittable
extension
fontawesome
gallery
icons
info
move
photogallery
popularity
popupviewer
revert
safefnrecode
sectiontoggle
styling
syntaxhighlighter4
testing
upgrade
usermanager
wrap
`

**Comment by spokekiller** [comment] 2020-06-27 15:00
@giterlizzi Works now. End-user error. Sorry. Confirmed to work with FF 77.0.1/Linux, and my setup stated above.
Thanks for your hard work.

**Comment by albertvilabsc** [comment] 2020-07-01 12:17
@giterlizzi 
The normal version of the template, in a future, with one update, will have a solution? Or only with the develop version?
If the normal version will have an update, more or less, in what month will appears the update?

**Comment by giterlizzi** [comment] 2020-07-01 13:32
@albertvilabsc
>The normal version of the template, in a future, with one update, will have a solution? Or only with the develop version?

The next release of template (actually in develop branch) solve issues introduced in Hogfather RC.

> If the normal version will have an update, more or less, in what month will appears the update?

Only few days (i'm waiting for another Hogfather RC for splitbrain/dokuwiki#3192)



Remember the workaround for Hogfather RC users:
- Disable "defer_js" option with "main" release of template
- Install the develop template version (develop branch)
- (optional) Upgrade jQuery to v3.5.1 (manually or using the "master branch" of DokuWiki) for solve a jQuery regression issue

**Comment by albertvilabsc** [comment] 2020-07-02 07:05
@giterlizzi 
Many thanks for your hard work!!
So, in few days will appears a new update of Hogfather RC for dokuwiki, and after, your template update?

**Comment by NiklasTheis** [comment] 2020-07-02 08:04
> 
> Remember the workaround for Hogfather RC users:
> 
>     * Disable "defer_js" option with "main" release of template
> 
>     * Install the develop template version (develop branch)
> 
>     * (optional) Upgrade jQuery to v3.5.1 (manually or using the "master branch" of DokuWiki) for solve a jQuery regression issue

These bullet points are one or the other, correct?

**Comment by millard73** [comment] 2020-07-13 23:40
> These bullet points are one or the other, correct?

The hamburger menu did not work for me until I did all three things (in that order). It's possible that just updating jQuery could have fixed it.

**Closed** 2020-07-29 12:48 UTC
Labels: bug
