### ISSUE TITLE
Issue after upgrading to rc2020-06-01 "Hogfather"

### ISSUE THREAD

**Issue by Jean-Daniel** [giterlizzi/dokuwiki-template-bootstrap3#483] opened 2020-06-01 15:33 UTC
### Description

After upgrading Dokuwiki, I have a issue very similar to #470, but with a standard vanilla install (no container, no docker, just a doku directory served by nginx + php-fpm).

Browser console show this:
```
[Error] Error: Bootstrap's JavaScript requires jQuery
	Global Code (bootstrap.min.js:6:89)
[Error] TypeError: undefined is not an object (evaluating 'b.fn')
	(anonymous function) (bootstrap3-typeahead.min.js:1:11741)
	(anonymous function) (bootstrap3-typeahead.min.js:1:199)
	Global Code (bootstrap3-typeahead.min.js:1:212)
[Error] ReferenceError: Can't find variable: DOKU_TPL
	(anonymous function) (fa.js:38)
	Global Code (fa.js:177)
[Error] TypeError: undefined is not a function (near '...jQuery("#qsearch").typeahead...')
	(anonymous function) (jquery.php:2:31678)
```

and I don't see any error in nginx/php logs.

### Steps to reproduce

1. Install latest doku version.
2. Perform basic configuration using the install script
3. Install bootstrap
4. enable it in admin settings.

### Versions

* [Bootstrap3 Template]
v2020-04-04
* [DokuWiki]
rc2020-06-01

* [Plugins]
* [PHP]
* [Browser]
Safari

**Comment by giterlizzi** [comment] 2020-06-01 17:40
Hi, thanks for reporting this issue for the next version of DokuWiki.

Please install the development version of the template.
The development version now uses the standard DokuWiki asset dispatcer for JS and CSS.

Regards,
Joseph

**Comment by MorbidNoodle** [comment] 2020-06-01 18:46
Seeing the same issue, I installed the devel version of the template. I can confirm that this fixed the navbar issues, and most other bootstrap items appear to work now. However I am still getting the same JQuery error on accordion objects.

**Comment by Jean-Daniel** [comment] 2020-06-01 22:19
Thanks. That fixed my issue.

**Comment by giterlizzi** [comment] 2020-06-02 13:20
@MorbidNoodle please add a screen of JS error console

**Comment by MorbidNoodle** [comment] 2020-06-02 15:39
So far the only bootstrap object I've seen with this error is the accordion, which is used in my sidebar page.

![image](https://user-images.githubusercontent.com/46251096/83539867-94316880-a4c5-11ea-9dcb-db494322dccf.png)

![image](https://user-images.githubusercontent.com/46251096/83539924-aad7bf80-a4c5-11ea-955e-2a10e215a3b4.png)

**Comment by Miro-Collas** [comment] 2020-06-03 01:06
I haven't tried the development branch yet, and it seems there are pending issues anwyay. Using the released code, we get:
`PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 57
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_EXIT - assumed 'DOKU_LEXER_EXIT' (this will throw an Error in a future version of PHP) in /home/fswiki/public_html/lib/plugins/bootswrapper/syntax/nav.php on line 74
PHP message: PHP Warning:  Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTE" while reading upstream`

**Comment by phy25** [comment] 2020-06-03 01:58
@Miro-Collas Those errors are caused by bootswrapper plugin. You may want to create an issue there.

**Comment by Miro-Collas** [comment] 2020-06-03 02:55
> @Miro-Collas Those errors are caused by bootswrapper plugin. You may want to create an issue there.

Oops, my bad. Thanks for pointing that out. I reported it there.

**Comment by mrazekpetr** [comment] 2020-06-03 04:30
Hi, I've got simillar issue after upgrade DokuWiki to version rc2020-06-01. I tried to install development version of the template, but it doesn't help. In my case, menu (settings/user) doesn't work. 
![js](https://user-images.githubusercontent.com/56604936/83595971-c5f90c80-a563-11ea-8d7f-17396706604b.PNG)

**Comment by phy25** [comment] 2020-06-03 05:12
As a workaround, you can [turn off `defer_js` (set it to`false`)](https://www.dokuwiki.org/config:defer_js) by adding it to `conf/local.php`, or by going to `/doku.php?do=admin&page=config` directly. Reference: https://github.com/splitbrain/dokuwiki/issues/3121

@mrazekpetr Your site does not seem to run the development version of the template. That lives in `develop` branch rather than `master`. You can try again by downloading it here: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/develop.zip

**Comment by Jean-Daniel** [comment] 2020-06-03 07:25
> Hi, I've got simillar issue after upgrade DokuWiki to version rc2020-06-01. I tried to install development version of the template, but it doesn't help. In my case, menu (settings/user) doesn't work.

Make sure you checkout the `develop` branch and not the `master` branch (I made that mistake first). And also make sure you clean the cache after that (both doku/data/cache and browser cache).

**Comment by giterlizzi** [comment] 2020-06-03 07:52
In development version all extra JS script (Bootstrap, TypeHead, AnchorJS, etc.) are loaded using include syntax (https://www.dokuwiki.org/devel:javascript#include_syntax) and dispatched via standard js.php file.

**Comment by wixaw** [comment] 2020-06-03 08:04
Hello
I have an issue with this template after upgrade ( core and template )
The path is absolute for loading css/js , not relative
see here https://www.adminwiki.fr/start

Thanks

**Comment by giterlizzi** [comment] 2020-06-03 08:18
@wixaw in according with your ``template.info.txt`` file (https://www.adminwiki.fr/lib/tpl/bootstrap3/template.info.txt) you have the master version of template. Please install the develop version of template via Extension Manager (manual install -- https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/develop.zip).

@all in this week a new version of template will be released if this development version work

Joseph

**Comment by wixaw** [comment] 2020-06-03 08:25
@giterlizzi thanks, Now i have develop/20200517 but now nothing is displayed :/

**Comment by mrazekpetr** [comment] 2020-06-03 08:34
> @mrazekpetr Your site does not seem to run the development version of the template. That lives in `develop` branch rather than `master`. You can try again by downloading it here: https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/develop.zip

Sorry, it's OK now.

**Comment by giterlizzi** [comment] 2020-06-03 08:38
> @giterlizzi thanks, Now i have develop/20200517 but now nothing is displayed :/

Have error in Development Console and/or in Apache error_log ?

**Comment by wixaw** [comment] 2020-06-03 09:31
I have only this on error log : 
`2020-06-03T11:26:30+02:00 mail.adminwiki.fr [Wed Jun 03 11:26:30.086426 2020] [proxy_fcgi:error] [pid 20783:tid 1951396912] [client 141.115.192.134:46936] AH01071: Got error 'PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /volume1/vhost_adminwiki.fr/lib/plugins/discussion/action.php on line 425\n'`

and the console this : 
```
GET https://www.adminwiki.fr/volume1/vhost_adminwiki.fr/lib/tpl/bootstrap3/css/fa-icons.less net::ERR_ABORTED 404
+10 more 
jquery.min.js:2 [Violation] 'setTimeout' handler took 58ms
js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1 Uncaught TypeError: jQuery(...).affix is not a function
    at HTMLDocument.<anonymous> (js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1)
    at HTMLDocument.dispatch (jquery.min.js:2)
    at HTMLDocument.v.handle (jquery.min.js:2)
    at Object.trigger (jquery.min.js:2)
    at HTMLDocument.<anonymous> (jquery.min.js:2)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at S.fn.init.trigger (jquery.min.js:2)
    at js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
(anonymous) @ js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
setTimeout (async)
(anonymous) @ js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
trigger @ jquery.min.js:2
(anonymous) @ js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
e @ jquery.min.js:2
t @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
c @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
jquery.min.js:2 [Violation] Added synchronous DOM mutation listener to a 'DOMNodeInserted' event. Consider using MutationObserver to make the page more responsive.
add @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
each @ jquery.min.js:2
each @ jquery.min.js:2
ke @ jquery.min.js:2
on @ jquery.min.js:2
bind @ jquery.min.js:2
(anonymous) @ js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1 Uncaught TypeError: jQuery(...).popover is not a function
    at js.php?t=bootstrap3&tseed=81357d92d1b3097b80fea52511d82456:1
```


the path "/volume1/vhost_adminwiki.fr/lib/tpl/bootstrap3/css/" is bad , it is on my server

**Comment by giterlizzi** [comment] 2020-06-03 10:02
@wixaw have "purged" your DokuWiki cache via:
- https://www.adminwiki.fr/lib/exe/css.php?purge=true
- https://www.adminwiki.fr/lib/exe/js.php?purge=true

Now work ;)

**Comment by wixaw** [comment] 2020-06-03 11:02
Wow nice, I did not know these functions

Thank you very much

**Comment by TalusUnheil** [comment] 2020-06-03 21:37
Hey there! I can confirm that [my problems](https://github.com/splitbrain/dokuwiki/issues/3131) got solved with manually installing the theme from the developer branch. :+1: 

One last question: Will the theme switch back to the 'normal' (master) version with the next 'official' release of the theme, or do I have to switch manually again?

**Comment by stormframe** [comment] 2020-06-03 22:39
mod_fcgid: stderr: PHP Warning: file_exists(): open_basedir restriction in effect. File(/usr/share/dokuwiki) is not within the allowed path(s): (/var/www/vhosts/fxxxx/:/tmp/) in /var/www/vhosts/xxxxx/lib/tpl/bootstrap3/iconify.php on line 39, referer: https://xxxx/doku.php?id=start&do=edit

Zeile auskommentiert .... schaut besser aus.

**Comment by rogerjames1994** [comment] 2020-06-04 09:49
Was also was having issues with the menus on the sidebar and nav not working. I download https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/develop.zip and the nav works at the top and the navbar but for some reason the icons dont show up on most of the menus on the sidebar. If I go to edit the page, and click Icon to add this, it does not seem to work. Below is a few pics one showing before the upgrade and the other one is after the upgrade and after the develop.zip. hopefully that will help.

![wikiupgrade1](https://user-images.githubusercontent.com/49854037/83742098-9ce98200-a61e-11ea-8dd4-ebaa77ad8fc1.PNG)
![wikiupgrade2](https://user-images.githubusercontent.com/49854037/83742100-9d821880-a61e-11ea-9ac0-c25e6dc9c8be.PNG)

**Comment by giterlizzi** [comment] 2020-06-04 15:17
@TalusUnheil Thanks for your feedback ;)
> One last question: Will the theme switch back to the 'normal' (master) version with the next 'official' release of the theme, or do I have to switch manually again?

When the new template version will be released (i hope in few days) go to in "Extension Manager" and click "upgrade" button.

**Comment by FloMiLe** [comment] 2020-06-04 15:36
I also installed https://github.com/giterlizzi/dokuwiki-template-bootstrap3/archive/develop.zip, but I noticed one more problem: the TOC does not work. One can click on the small button to expand the TOC, but it is not populated.

**Comment by f4kt** [comment] 2020-06-04 20:01
First of all thanks for this great template :)

With dokuwiki branch stable, in a **farm installation**, and after installing the given development version URL, I see a problem like this in each "animal" site:

![screen](https://user-images.githubusercontent.com/29780020/83804511-8d197e80-a6ae-11ea-876a-4e461949f5fa.png)

Thanks in advance.

**Comment by f4kt** [comment] 2020-06-04 20:19
I also realize that the Configuration page in a animal site is blank (...do=admin&page=config), without errors in Console

**Comment by daamien** [comment] 2020-06-12 09:21
Disabling the `defer_js` option fixed the problem for us. This is the easiest workaround.

**Comment by f4kt** [comment] 2020-06-13 19:54
@daamien if defer_js is disabled:
1) The menu is not showing and some errors appear in the console
2) The plugin list does not show
(maybe yours is a non-farm installation, I was talking about a farm one)

**Comment by intervisionlord** [comment] 2020-06-18 08:34
still does not work with collapsable accodrion even after all cache purging
no reaction after click on panel header
```
TypeError: can't convert o to string 2 js.php:1:131003
    test self-hosted:2739
    l https://*********/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    jQuery 2
        each
        each
    l https://*********/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    <анонимный> https://wiki.twr.su/lib/exe/js.php?t=bootstrap3&tseed=98c951d1500548f34fdf077dbc702956:1
    jQuery 2
        dispatch
        handle
```

**Comment by giterlizzi** [comment] 2020-06-29 12:25
@intervisionlord This is jQuery regression issue for v3.5.0 (https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/)

Change the ``JQ_VERSION`` to ``3.5.1`` in ``lib/script/jquery/versions`` and run ``update.sh`` script.

@SoarinFerret have opened splitbrain/dokuwiki#3192 PR for update jQuery to v3.5.1 in DokuWiki.

**Closed** 2020-07-29 12:48 UTC
Labels: bug, resolved, support

**Comment by f4kt** [comment] 2020-08-02 15:54
Any news about getting a blank page at Configuration page (do=admin&page=config) in the farm animal?

**Comment by phy25** [comment] 2020-08-02 17:20
> Any news about getting a blank page at Configuration page (do=admin&page=config) in the farm animal?

Please check https://www.dokuwiki.org/faq:blankpage for troubleshooting steps.

**Comment by f4kt** [comment] 2020-08-02 22:19
Thanks a lot @phy25. The reason was that some old plugins (authLDAP,...) were disabled but yet installed. As soon as I have deleted them everything has gone right.

**Comment by fibinicci** [comment] 2020-10-28 18:49
> @intervisionlord This is jQuery regression issue for v3.5.0 (https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/)
> 
> Change the `JQ_VERSION` to `3.5.1` in `lib/script/jquery/versions` and run `update.sh` script.
> 

I have checked what you mentioned but I already have the 3.5.1 version (loaded the v2020-08-28 of the template just a few days ago)
And I still have the following problem:
